<!DOCTYPE html>
<html lang="de"><head>
<script src="auftakt_arbeitsgruppe_files/libs/clipboard/clipboard.min.js"></script>
<script src="auftakt_arbeitsgruppe_files/libs/quarto-html/tabby.min.js"></script>
<script src="auftakt_arbeitsgruppe_files/libs/quarto-html/popper.min.js"></script>
<script src="auftakt_arbeitsgruppe_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="auftakt_arbeitsgruppe_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="auftakt_arbeitsgruppe_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="auftakt_arbeitsgruppe_files/libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Dr.&nbsp;Oliver Schacht und Jan Teichert-Kluge">
  <title>Willkommen in der Arbeitsgruppe</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="auftakt_arbeitsgruppe_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="auftakt_arbeitsgruppe_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="auftakt_arbeitsgruppe_files/libs/revealjs/dist/theme/quarto-331051d76a89ac140b3aa95b2c0a6cec.css">
  <link rel="stylesheet" href="_extensions/studienstiftung-theme/theme_revealjs.scss">
  <link href="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <script src="auftakt_arbeitsgruppe_files/libs/quarto-diagram/mermaid.min.js"></script>
  <script src="auftakt_arbeitsgruppe_files/libs/quarto-diagram/mermaid-init.js"></script>
  <link href="auftakt_arbeitsgruppe_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="_extensions/studienstiftung-theme/assets/logo.svg" data-background-position="98% 2%" data-background-size="30%" class="quarto-title-block center">
  <h1 class="title">Willkommen in der Arbeitsgruppe</h1>
  <p class="subtitle">Künstliche Intelligenz und das „Warum“</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Dr.&nbsp;Oliver Schacht und Jan Teichert-Kluge
</div>
        <p class="quarto-title-affiliation">
            Sommerakademie Leysin 2026 · Studienstiftung des deutschen Volkes
          </p>
    </div>
</div>

</section>
<section>
<section id="auftakt" class="title-slide slide level1 center">
<h1>Auftakt</h1>

</section>
<section id="willkommen" class="slide level2">
<h2>Willkommen</h2>
<p>Schön, dass du dabei bist ​🙂​</p>
<p>Die nächsten <strong>8 Tage</strong> arbeiten wir in dieser Arbeitsgruppe an der Schnittstelle von <strong>Maschinellen Lernen</strong>, <strong>Statistik</strong> und <strong>Kausaler Inferenz</strong>.</p>
<div class="fragment">
<blockquote>
<p>Wir untersuchen nicht nur, welche Korrelationen Daten enthalten, sondern wann diese Muster etwas über <strong>Ursache und Wirkung</strong> aussagen.</p>
</blockquote>
<p>Wir werden zunächst zusammen die Grundlagen erarbeiten und dann in Gruppenprojekten vertiefen.</p>
</div>
<aside class="notes">
<p>0–3 Minuten. Zuerst nur die Beobachtung vorlesen und zehn Sekunden raten lassen: „Was könnte hier passiert sein?“ Erst nach zwei oder drei Wortmeldungen weiterschalten. Die Grafik wechselt dann zur gemeinsamen Ursache Alkohol. Leitidee: Ein auffälliges Muster genügt nicht für eine Ursache.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="heute" class="slide level2">
<h2>Heute</h2>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Programmpunkt</th>
<th style="text-align: right;">Format</th>
<th>Frage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td style="text-align: right;">Ankommen &amp; Orientierung</td>
<td>Wer sind wir, was ist diese AG?</td>
</tr>
<tr class="even">
<td>2</td>
<td style="text-align: right;">Vorstellungsrunde</td>
<td>Welche Erfahrungen und Erwartungen sind im Raum?</td>
</tr>
<tr class="odd">
<td>3</td>
<td style="text-align: right;">Motivationsbeispiele</td>
<td>Wann täuscht Korrelation?</td>
</tr>
<tr class="even">
<td>4</td>
<td style="text-align: right;">Gruppenarbeit &amp; Projekte</td>
<td>Wie arbeiten wir in den nächsten Tagen?</td>
</tr>
</tbody>
</table>
<aside class="notes">
<p>Diese Folie ist die Taktung für die Dozierenden. Bei großer Gruppe die Vorstellungsrunde straff halten und den vierten Forschungsfall als Backup behandeln.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="die-arbeitsgruppe" class="title-slide slide level1 center">
<h1>Die Arbeitsgruppe</h1>

</section>
<section id="das-sind-wir" class="slide level2">
<h2>Das sind wir</h2>
<div class="columns">
<div class="column" style="width:48%;">
<h3 id="dr.-oliver-schacht">Dr.&nbsp;Oliver Schacht</h3>
<p><img data-src="figs/oliver.png" alt="Portrait von Oliver" height="190"></p>
<ul>
<li>Promotion in Statistik / <strong>Causal Machine Learning</strong></li>
<li>Arbeiten u.a. zum Einsatz kausaler KI in der Halbleiterfertigung</li>
<li>Mitwirkung am Python-Paket <strong>DoubleML</strong></li>
<li>Erfahrung im Data Science Consulting bei Economic AI</li>
</ul>
</div><div class="column" style="width:48%;">
<h3 id="jan-teichert-kluge">Jan Teichert-Kluge</h3>
<p><img data-src="figs/jan-teichert-kluge_sqr.jpg" alt="Portrait von Jan" height="190"></p>
<ul>
<li>Promotion in Statistik / <strong>Causal Machine Learning</strong></li>
<li>Arbeiten u.a. zu Kausaler Inferenz mittels Deep Learning</li>
<li>Mitwirkung am Python-Paket <strong>DoubleML</strong></li>
<li>Langjährige Industrie-Erfahrung in Data-Science-Teams</li>
</ul>
</div></div>
</section>
<section id="inhalte-der-arbeitsgruppe" class="slide level2">
<h2>Inhalte der Arbeitsgruppe</h2>
<ul>
<li><p>Die AG behandelt die Grundlagen der kausalen Inferenz (mit ML)</p>
<ul>
<li>Zentrale Konzepte der kausalen Inferenz:
<ul>
<li>Potenzielle Outcomes und kontrafaktische Szenarien</li>
<li>Definition kausaler Effekte</li>
<li>Grafische Modelle</li>
</ul></li>
<li>Statistische Methoden zur Untersuchung von Kausalität:
<ul>
<li>Randomisierte Experimente</li>
<li>Beobachtungsstudien</li>
<li>Identifikation kausaler Effekte</li>
<li>Schätzung mit ML</li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="lernziele-der-arbeitsgruppe" class="slide level2">
<h2>Lernziele der Arbeitsgruppe</h2>
<ul>
<li><p>Wir wollen methodische Skills vermitteln, die in Studium, Beruf und Forschung hilfreich sein werden, z.B.,</p>
<ul>
<li>wie man allgemeine Intuitionen auf eine handhabbare Weise formalisiert</li>
<li>wie man Hypothesen ableitet, die anhand von Daten getestet werden können</li>
<li>problemorientiertes und selbstorganisiertes Lernen</li>
<li>die Fähigkeit, Assoziation von Kausalität zu unterscheiden – sehr wichtig für Ihr ganzes Leben! 🙂​</li>
</ul></li>
</ul>
</section>
<section id="gemeinsame-vs.-gruppenarbeit" class="slide level2">
<h2>Gemeinsame vs.&nbsp;Gruppenarbeit</h2>
<div class="columns">
<div class="column" style="width:48%;">
<h3 id="gemeinsam">Gemeinsam</h3>
<ul>
<li>Grundlagen zu ML und Kausalinferenz</li>
<li>technische Unterstützung: Python, VS Code und Streamlit</li>
<li>Vorstellung und Diskussion der Gruppenprojekte</li>
</ul>
</div><div class="column" style="width:48%;">
<h3 id="in-den-gruppen">In den Gruppen</h3>
<ul>
<li>ein Vertiefungsthema eigenständig erschließen</li>
<li>eine kausale Fragestellung inkl. Annahmen, Schätzung usw. beantworten</li>
<li>eine kleine interaktive App oder Analyse bauen</li>
<li>Annahmen, Grenzen und offene Fragen sichtbar machen</li>
</ul>
</div></div>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Uns geht es nicht um eine Referatsreihe. Die Gruppenarbeiten sind ein Labor. Es geht darum mit Daten und Methodiken zu arbeiten und dabei zu lernen!</p>
</div>
</div>
</div>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Die abschließenden Präsentationen sind keine Prüfungen! Sie sind Anregungspunkt für Diskussionen.</p>
</div>
</div>
</div>
</section>
<section id="wer-seid-ihr" class="slide level2">
<h2>Wer seid ihr?</h2>
<p>Wir wollen euch kennenlernen, z.B.,</p>
<ul>
<li>Name, Studienfach</li>
<li>Ein Thema, das dich wissenschaftlich beschäftigt</li>
<li>Was du gerne im Rahmen der Arbeitsgruppe verstehen würdet</li>
</ul>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Bist du schonmal auf einen Trugschluss durch Korrelationen gestoßen?</p>
</div>
</div>
</div>
<aside class="notes">
<p>10–20 Minuten. Eine sichtbare Uhr hilft. Nach etwa zwölf Minuten aktiv schließen und ankündigen, dass Fachinteressen beim Projektmatching wieder aufgegriffen werden.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="positionsbarometer" class="slide level2 scrollable">
<h2>Positionsbarometer</h2>
<p>Stellt euch gemäß eurer Position im Raum auf.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Linkes Ende</th>
<th>Rechtes Ende</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>stimme gar nicht zu</td>
<td>stimme voll zu</td>
</tr>
</tbody>
</table>
<p>Aussagen:</p>
<div class="fragment">
<ol type="1">
<li>„Ein sehr gutes ML-Modell liefert automatisch gute Entscheidungen.“</li>
</ol>
</div>
<div class="fragment">
<ol start="2" type="1">
<li>„Kausalität ist vor allem gesunder Menschenverstand.“</li>
</ol>
</div>
<div class="fragment">
<ol start="3" type="1">
<li>„Je größer Modell und Datenmenge, desto besser wird der Output.“</li>
</ol>
</div>
<aside class="notes">
<p>20–25 Minuten. Nach jeder Aussage zwei kontrastierende Stimmen einholen, nicht auflösen. Die Aussagen werden im Verlauf der Woche präziser.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section></section>
<section>
<section id="warum-das-warum-zählt" class="title-slide slide level1 center">
<h1>Warum das „Warum“ zählt</h1>

</section>
<section id="schokolade-als-nobelstrategie" class="slide level2">
<h2>Schokolade als Nobelstrategie?</h2>
<div class="columns">
<div class="column" style="width:43%;">
<blockquote>
<p>Länder mit höherem Schokoladenkonsum haben mehr Nobelpreisträger:innen pro Kopf.</p>
</blockquote>
<div class="fragment">
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Mögliche Diagnose: Confounding.</strong> Wohlstand, Bildungs- und Forschungsinfrastruktur erhöhen plausibel sowohl den Schokoladenkonsum als auch die Chance auf wissenschaftliche Spitzenleistungen.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:57%;">
<p><img data-src="figs/nobelpreise.png" alt="Positive Korrelation zwischen Schokoladenkonsum und Nobelpreisträgerinnen und Nobelpreisträgern pro Kopf." height="375"></p>
</div></div>
</section>
<section id="attraktivität-schlägt-auf-den-charakter" class="slide level2">
<h2>Attraktivität schlägt auf den Charakter?</h2>
<div class="columns">
<div class="column" style="width:43%;">
<blockquote>
<p>Auf einer Dating-Plattform erhalten sehr attraktive Profile kürzere, weniger persönliche Nachrichten.</p>
</blockquote>
<div class="fragment">
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Mögliche Diagnose: Selektions- bzw. Colliderbias.</strong> Wer nur Menschen auf Datingapps betrachtet, konditioniert auf einen Auswahlprozess. Diese Teilmenge liefert nicht zwangsläufig valide Schlüsse auf die Population.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:57%;">
<div style="height: 330px; overflow: hidden;">
<p><img src="figs/dating_collider.png" alt="Lehrkarte über eine Beobachtung aus Dating-Apps" style="width: 100%; margin: 0; transform: translateY(0);"></p>
</div>
</div></div>
</section>
<section id="ki-und-geisteswissenschaftsabschlüsse" class="slide level2">
<h2>KI und Geisteswissenschaftsabschlüsse</h2>
<div class="columns">
<div class="column" style="width:43%;">
<blockquote>
<p>Die weltweite Verbreitung von KI und die Zahl der Geisteswissenschaftsabschlüsse verlaufen fast parallel.</p>
</blockquote>
<div class="fragment">
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Mögliche Diagnose: Scheinkorrelation.</strong> Eine gemeinsame Zeitachse kann sehr unterschiedliche Größen gleichzeitig verändern. Ohne plausiblen Wirkmechanismus und Vergleichsdesign ist die fast perfekte Korrelation keine Evidenz für einen Effekt.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:57%;">
<p><img data-src="figs/adoption.png" alt="Zwei stark ähnlich verlaufende Zeitreihen."></p>
</div></div>
</section>
<section id="der-mindestlohn-macht-alles-teuerer11" class="slide level2">
<h2>Der Mindestlohn macht alles teuerer!!11!</h2>
<div class="columns">
<div class="column" style="width:40%;">
<blockquote>
<p>Nach einer Mindestlohnerhöhung steigen auch die Preise für Brot und Brötchen.</p>
</blockquote>
<div class="fragment">
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Mögliche Diagnose: gemeinsame Trends und Rückkopplung.</strong> Lebenshaltungskosten, Branchenkosten und politische Reaktionen können Löhne und Preise zugleich bewegen. Ein glaubwürdiger Vergleich könnte etwa ein <strong>Difference-in-Differences</strong>-Design nutzen.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:60%;">
<p><img data-src="figs/broetchen.png" alt="Grafik zur Entwicklung von Mindestlohn und Preisen in mehreren Branchen." height="500"></p>
</div></div>
</section>
<section id="wein-als-heimlicher-covid-impfstoff" class="slide level2">
<h2>Wein als heimlicher Covid Impfstoff?</h2>
<div class="columns">
<div class="column" style="width:45%;">
<blockquote>
<p>In Beobachtungsdaten scheint regelmäßiger Weinkonsum mit einem niedrigeren COVID-Risiko einherzugehen.</p>
</blockquote>
<div class="fragment">
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Mögliche Diagnose: Confounding.</strong> Alter, Einkommen, Gesundheit, Zugang zu Versorgung und Kontaktverhalten können sowohl den Konsum von Wein als auch das Erkrankungsrisiko beeinflussen.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:55%;">
<p><img data-src="figs/wein-covid2.png" alt="Lehrillustration zu Wein als scheinbarem Schutzfaktor gegen COVID."></p>
</div></div>
</section>
<section id="krankenhausaufenthalte-machen-krank" class="slide level2">
<h2>Krankenhausaufenthalte machen krank?</h2>
<div class="columns">
<div class="column" style="width:43%;">
<blockquote>
<p>Patient:innen mit langen Krankenhausaufenthalten haben später im Mittel einen schlechteren Gesundheitszustand.</p>
</blockquote>
<div class="fragment">
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Mögliche Diagnose: umgekehrte Kausalität.</strong> Häufig macht nicht der Aufenthalt krank; ein schwerer Ausgangszustand führt zugleich zu längerer Verweildauer und schlechterer späterer Gesundheit.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:57%;">
<div style="overflow: hidden;">
<p><img src="figs/hospital_stay.png" alt="Lehrkarte zu Krankenhausaufenthalten und Gesundheit" style="width: 100%; margin: 0;"></p>
</div>
</div></div>
</section>
<section id="ausgebuchte-unterkünfte-schmerzende-augen" class="slide level2">
<h2>Ausgebuchte Unterkünfte, schmerzende Augen</h2>
<div class="columns">
<div class="column" style="width:30%;">
<blockquote>
<p>Regionen mit vielen ausgebuchten Airbnbs verzeichnen zugleich auffällig viele Suchanfragen nach „Augenschmerzen“.</p>
</blockquote>
<div class="fragment">
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Mögliche Diagnose: gemeinsame Ursache.</strong> Die Sonnenfinsternis vom 8. April 2024 brachte Reisende auf ihren Verlauf und führte zugleich zu mehr Suchanfragen nach Beschwerden rund um das Beobachten der Finsternis.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:70%;">
<div class="quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row quarto-layout-valign-center">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img data-src="figs/airbnb.jpeg" alt="Karte zu Airbnb- und Vrbo-Buchungen entlang des Verlaufs der Sonnenfinsternis."></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img data-src="figs/augenschmerzen.jpeg" alt="Karte zum Suchvolumen für Augenbeschwerden in den USA."></p>
</div>
</div>
</div>
</div></div>
</section>
<section id="covid-booster-und-sterblichkeitsraten" class="slide level2">
<h2>Covid Booster und Sterblichkeitsraten</h2>
<div class="columns">
<div class="column" style="width:43%;">
<blockquote>
<p>In den Gesamtdaten ist die Sterblichkeit unter den geboosterten Patient:innen höher.</p>
</blockquote>
<div class="fragment">
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><strong>Mögliche Diagnose: Simpsons Paradox.</strong> Wenn Geboosterte im Schnitt deutlich älter sind, dominieren sie in den Rohdaten. Innerhalb jeder Altersgruppe kann die Sterblichkeit dennoch niedriger sein; erst die Altersstandardisierung macht den Vergleich sinnvoll.</p>
</div>
</div>
</div>
</div>
</div><div class="column" style="width:57%;">
<p><img data-src="figs/covid.png" alt="Tabelle mit Sterblichkeitsraten nach Impfstatus und Altersgruppe"></p>
</div></div>
</section>
<section id="vom-muster-zum-argument" class="slide level2">
<h2>Vom Muster zum Argument</h2>
<ul>
<li class="fragment"><p><strong>Kausale Frage</strong><br>
Was würde eine Intervention bewirken?</p></li>
<li class="fragment"><p><strong>Counterfactual</strong><br>
Was wäre sonst geschehen?</p></li>
<li class="fragment"><p><strong>Design &amp; Annahmen</strong><br>
Warum ist der Vergleich glaubwürdig?</p></li>
<li class="fragment"><p><strong>Schätzung</strong><br>
Welche Zahl folgt aus den Daten?</p></li>
<li class="fragment"><p><strong>Interpretation</strong><br>
Was zeigt sie — und was nicht?</p></li>
</ul>
<div class="fragment">
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Ein (ML-)Modell kann eine Zahl ausgeben. Eine kausale Analyse muss zusätzlich begründen, warum diese Zahl als kausaler Effekt interpretiert werden darf.</p>
</div>
</div>
</div>
</div>
</section></section>
<section>
<section id="die-nächsten-tage" class="title-slide slide level1 center">
<h1>Die nächsten Tage</h1>

</section>
<section id="ablaufplan" class="slide level2">
<h2>Ablaufplan</h2>
<div class="cell" data-reveal="true" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  A["19.08.&lt;br/&gt;Auftakt &amp; Setup"] --&gt; B["20.08.&lt;br/&gt;ML &amp; Kausalinferenz"]
  B --&gt; C["21.–22.08.&lt;br/&gt;Projekt-Sprint"]
  C --&gt; D["24.–25.08.&lt;br/&gt;Gruppenpräsentationen"]
  D --&gt; E["26.08.&lt;br/&gt;Synthese &amp; Feedback"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<ul>
<li>Heute setzen wir noch zusammen Python auf und erkunden Streamlit.</li>
<li>Morgen gibt es interaktive Input Sessions zu ML und kausaler Inferenz</li>
<li>Am 21.08. und 22.08. ist Zeit für die Gruppenarbeit</li>
<li>Am 23.08. ist frei; die meisten Präsentationen verteilen sich auf den 24. und 25.08.</li>
</ul>
<aside class="notes">
<p>35–38 Minuten. Die genauen Uhrzeiten stehen auf der Ablaufplan-Seite; hier nur den Rhythmus zeigen: Grundlagen → Gruppenarbeit → gegenseitiges Lernen → Synthese.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="themen-der-gruppenarbeit" class="slide level2">
<h2>Themen der Gruppenarbeit</h2>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Thema</th>
<th>Kernfrage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>🏥 <strong>Randomisierte Experimente / Medizin</strong></td>
<td>Was leistet ein RCT?</td>
</tr>
<tr class="even">
<td>🔍 <strong>Explainable ML / AI</strong></td>
<td>Warum sind Modell-Erklärungen nicht automatisch kausal?</td>
</tr>
<tr class="odd">
<td>💬 <strong>Causality and LLMs</strong></td>
<td>Können Sprachmodelle kausal schlussfolgern oder beim Forschen helfen?</td>
</tr>
<tr class="even">
<td>🕸️ <strong>DAGs / Causal Discovery</strong></td>
<td>Welche Strukturannahmen lassen sich begründen oder aus Daten eingrenzen?</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:50%;">
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Thema</th>
<th>Kernfrage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>🎯 <strong>Causal Inference with ML</strong></td>
<td>Für wen wirkt eine Maßnahme — und wie hilft ML?</td>
</tr>
<tr class="even">
<td>📐 <strong>Tools: RDD / DiD</strong></td>
<td>Was lernen wir aus Cutoffs, und parallelen Trends?</td>
</tr>
<tr class="odd">
<td>🎲 <strong>Bayesian Methods</strong></td>
<td>Wie werden Vorwissen und Unsicherheit transparent modelliert?</td>
</tr>
</tbody>
</table>
</div><div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Die Website liefert zu jedem Thema einen Einstieg, eine Demo und offene Fragen. Das Projekt beginnt nicht mit einer fertigen Antwort, sondern mit einer guten Entscheidung darüber, <strong>was ihr zeigen wollt</strong>.</p>
</div>
</div>
</div>
</div>
</section>
<section id="themengestaltung" class="slide level2">
<h2>Themengestaltung</h2>
<p>Wählt nicht nur nach dem interessantesten Schlagwort.</p>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Prüffrage</th>
<th>Gute Antwort</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Neugier</strong></td>
<td>Wir wollen diese Frage wirklich verstehen.</td>
</tr>
<tr class="even">
<td><strong>Lernziel</strong></td>
<td>Das Thema ergänzt unser Vorwissen sinnvoll.</td>
</tr>
<tr class="odd">
<td><strong>Machbarkeit</strong></td>
<td>In wenigen Tagen können wir ein klares Lernartefakt bauen.</td>
</tr>
<tr class="even">
<td><strong>Beitrag</strong></td>
<td>Die Gruppe kann anderen eine Annahme, Methode oder Grenze verständlich machen.</td>
</tr>
</tbody>
</table>
</section>
<section id="ein-gutes-projekt" class="slide level2">
<h2>Ein gutes Projekt</h2>
<p>Am Ende entwickelt jede Gruppe eine wissenschaftlich fundierte <strong>Mini-Station</strong>.</p>
<div class="columns">
<div class="column" style="width:48%;">
<h3 id="argument">Argument</h3>
<ul>
<li>klare kausale Frage</li>
<li>Kernidee oder Methode</li>
<li>eine explizite Annahme</li>
<li>Bezug zu einer Studie, einem Design oder einer Kontroverse</li>
<li>Grenzen der Schlussfolgerung</li>
</ul>
</div><div class="column" style="width:48%;">
<h3 id="interaktion">Interaktion</h3>
<ul>
<li>Simulation, Analyse oder Visualisierung</li>
<li>mindestens ein Regler, Vergleich oder Szenario</li>
<li>eine sichtbare Annahme oder Grenze</li>
<li>nachvollziehbar für die anderen Gruppen</li>
</ul>
</div></div>
<blockquote>
<p>Eine gute App macht nicht nur Ergebnisse sichtbar. Sie macht ein <strong>wissenschaftliches Argument erfahrbar</strong>.</p>
</blockquote>
</section>
<section id="kein-dashboard-sondern-eine-erkenntnis" class="slide level2">
<h2>Kein Dashboard, sondern eine Erkenntnis</h2>
<p>Nicht:</p>
<blockquote>
<p>„Hier sind viele Plots und Kennzahlen.“</p>
</blockquote>
<p>Sondern:</p>
<blockquote>
<p>„Wenn diese Annahme verletzt ist, kippt die Interpretation.“<br>
„Wenn wir für diese Variable adjustieren, ändert sich der Estimand.“<br>
„Wenn wir Vorhersage mit Wirkung verwechseln, treffen wir eine andere Entscheidung.“</p>
</blockquote>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Die wichtigste Leistung eines Projekts ist nicht die größte technische Komplexität, sondern eine fundierte (kausale) Analyse.</p>
</div>
</div>
</div>
</section>
<section id="darstellung-der-projekte-auf-der-website" class="slide level2">
<h2>Darstellung der Projekte auf der Website</h2>
<div class="columns">
<div class="column" style="width:48%;">
<h3 id="option-1-projektseite-in-markdown">Option 1: Projektseite in Markdown</h3>
<ul>
<li>Ordner aus der Vorlage kopieren</li>
<li><strong>projekt.md</strong> mit Titel, Team und Erklärung ausfüllen</li>
<li>Plots oder Screenshots hinzufügen</li>
<li>gut für Theorie, Case Study und Dokumentation</li>
</ul>
</div><div class="column" style="width:48%;">
<h3 id="kür-interaktive-streamlit-app">Kür: Interaktive Streamlit-App</h3>
<ul>
<li>zusätzlich <strong>app.py</strong> im Projektordner</li>
<li>Slider, Simulationen und eigene Visualisierungen</li>
<li>nur Pakete aus den vorhandenen Requirements</li>
<li>wir helfen beim Debugging und bei der Umsetzung</li>
</ul>
</div></div>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Ein Fehler in einem Projekt legt nicht die gesamte Website lahm. Ausprobieren ist ausdrücklich Teil der Arbeitsgruppe.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="erste-eigene-frage" class="title-slide slide level1 center">
<h1>Erste eigene Frage</h1>

</section>
<section id="causal-claims-clinic" class="slide level2 scrollable">
<h2>Causal Claims Clinic</h2>
<ol type="1">
<li><strong>Allein · 1 Minute:</strong> Wähle eine Behauptung oder Studienidee.</li>
<li><strong>Zu zweit · 3 Minuten:</strong> Formuliert Treatment, Outcome und einen möglichen Bias.</li>
<li><strong>Zu viert · 4 Minuten:</strong> Skizziert ein Design oder eine Annahme.</li>
<li><strong>Plenum · 3 Minuten:</strong> Eine Gruppe teilt ihre präziseste Frage.</li>
</ol>
<aside class="notes">
<p>47–58 Minuten. Diese Struktur folgt dem Gedanken von 1–2–4–All: Erst selbst denken, dann Vergleichsmöglichkeiten erweitern. Bei knapper Zeit Plenum auf zwei Beiträge begrenzen.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>
</section>
<section id="ausgangspunkte" class="slide level2">
<h2>Ausgangspunkte</h2>
<p>Wählt eine Karte oder bringt eine eigene Frage ein:</p>
<ul>
<li>„Mentoring erhöht Studienerfolg.“</li>
<li>„KI-Feedback verbessert wissenschaftliches Schreiben.“</li>
<li>„Homeoffice steigert Produktivität.“</li>
<li>„Screeningprogramme verbessern Gesundheit.“</li>
<li>„Eine Preiserhöhung senkt Nachfrage.“</li>
<li>„Explainable AI erhöht Vertrauen in Entscheidungen.“</li>
<li>„LLMs verbessern kausales Denken.“</li>
</ul>
<p><strong>Ziel:</strong> Nicht sofort die richtige Methode nennen. Zuerst die Frage so präzise formulieren, dass eine Methode überhaupt beurteilt werden kann.</p>
</section>
<section id="causal-canvas" class="slide level2">
<h2>Causal Canvas</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Baustein</th>
<th>Leitfrage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Einheit</td>
<td>Wer oder was wird betrachtet?</td>
</tr>
<tr class="even">
<td>Treatment</td>
<td>Welche Intervention oder Variation interessiert uns?</td>
</tr>
<tr class="odd">
<td>Outcome</td>
<td>Was soll sich verändern?</td>
</tr>
<tr class="even">
<td>Counterfactual</td>
<td>Was wäre ohne Treatment geschehen?</td>
</tr>
<tr class="odd">
<td>Naiver Vergleich</td>
<td>Welche Auswertung läge zunächst nahe?</td>
</tr>
<tr class="even">
<td>Gefahr</td>
<td>Warum könnte dieser Vergleich irreführend sein?</td>
</tr>
<tr class="odd">
<td>Nächster Schritt</td>
<td>Experiment, DAG, RDD, DiD, ML, Bayes oder Sensitivität?</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Bewahrt eure Canvas auf. Sie kann der Ausgangspunkt für eine Themenpräferenz oder ein eigenes Projekt werden.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="abschluss" class="title-slide slide level1 center">
<h1>Abschluss</h1>

</section>
<section id="für-morgen" class="slide level2 scrollable">
<h2>Für morgen</h2>
<ol type="1">
<li><p><strong>Einführung in Machine Learning</strong><br>
Was kann ein Modell aus Daten lernen?</p></li>
<li><p><strong>Einführung in Kausale Inferenz</strong><br>
Was müssen wir zusätzlich wissen oder annehmen, um aus Daten über Interventionen zu lernen?</p></li>
</ol>
<div class="callout callout-important callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p>Die Leitfrage für morgen:<br>
<strong>Was wäre passiert, wenn wir anders gehandelt hätten?</strong></p>
</div>
</div>
</div>
</section>
<section id="fazit-für-heute" class="slide level2">
<h2>Fazit für heute</h2>
<ul>
<li>Die AG ist ein Labor: Methodisches Arbeiten, kausale Argumente und Prototypen zählen.</li>
<li>Kausalität beginnt mit einer präzisen Frage, nicht mit einem Algorithmus.</li>
<li>Gute Projekte verbinden Methode, Annahmen, Interaktion und Grenzen.</li>
<li>Im Kern geht es bei kausaler Inferenz um die Frage, was unter einer anderen Entscheidung passiert wäre.</li>
</ul>
</section>
<section id="bild--und-quellenhinweise" class="slide level2">
<h2>Bild- und Quellenhinweise</h2>
<ul>
<li>Schuhe im Bett / Kopfschmerzen: <a href="https://www.bradyneal.com/causal-inference-course#course-textbook/">Brady Neal, <em>Causal Inference from a Machine Learning Perspective</em></a></li>
<li>Weitere Quellen und Einordnungen sind direkt in den jeweiligen Lehrgrafiken angegeben.</li>
<li>Die Wein-Grafik ist eine eigens für diese Präsentation erzeugte Lehrillustration; sie stellt keine empirische Evidenz dar.</li>
</ul>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Künstliche Intelligenz und das Warum · Arbeitsgruppenauftakt</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="auftakt_arbeitsgruppe_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: true,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Kopiert");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Kopiert");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>